version: '3.3'

services:

  mongo:
    image: "mongo"
    container_name: "historicaldb"
    ports: 
      - 27019:27017
    expose: 
      - "27019"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=historical

volumes:
  mongo_data:
